#!/usr/bin/env bash
# @file open_swagger_ui_with
# Crank up an instance of Swagger UI to display doc for the given
# swagger file
# Usage: ./open_swagger_ui_with swagger[.json|.yaml] [port]
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

SWAGGER_FILE="$1"
SWAGGER_UI_IMAGE='swaggerapi/swagger-ui'
SWAGGER_UI_PORT="${2:-8080}"
SWAGGER_URL="http://localhost:$SWAGGER_UI_PORT/"

[[ -z "$SWAGGER_FILE" ]] && {
    read -p "What swagger file do you want show in swagger-ui? " -r
    echo
    SWAGGER_FILE="$REPLY"
}

BIN='/usr/local/bin'
[[ -e "$BIN/open_swagger_ui_with" ]] || ln -sf "$PWD/open_swagger_ui_with" $BIN

# start swagger-ui contianer -------------------------------------------------

pgrep -f docker > /dev/null || {
    echo "Your system doesn't appear to be running the Docker daemon."
    echo "To run swagger-ui in a container, I need to use docker."
    echo "Please make sure Docker is running and try again."
    exit 1
}

docker ps -a | grep "$SWAGGER_UI_IMAGE" > /dev/null 2>&1 && {
    docker ps -a | grep "$SWAGGER_UI_IMAGE" | \
        awk '{print $1}' | \
        xargs docker rm -fv > /dev/null 2>&1
}

docker run -d --name swagguer-ui \
    -p "$SWAGGER_UI_PORT":8080 \
    -e SWAGGER_JSON="/spec/$SWAGGER_FILE" \
    -v "$PWD":/spec \
    "$SWAGGER_UI_IMAGE" \
    > /dev/null 2>&1

# Open brower using swagger ui view on the swagger definition ----------------

[[ "$OSTYPE" == "darwin"* ]] && open "$SWAGGER_URL"
echo "View Swagger-UI for $SWAGGER_FILE in your browser using $SWAGGER_URL"