#!/usr/bin/env bash
# @file vke_auth
# Authenticate with VMware Kubernetes Engine service using account credentials
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

source "vke_env.sh"

## Authentication state held in ~/vke-cli/vke-config but can't find
## a way to determine if I have an expired session, so just login in each time

erun vke account login -t "$VKE_CSP_ORG_ID" -r "$VKE_TOKEN"
