#!/usr/bin/env bash
# @file vke_addon_wavefront
# Add Wavefront proxy and collector to existing Smart Cluster
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

# shellcheck disable=SC1091
source vke_env.sh

# helper functions -----------------------------------------------------------

clean_up () {
    EXIT_CODE=$?
    echo
    read -p "Shall I remove all Wavefront related objects? [y/N] " -n 1 -r
    [[ $REPLY =~ ^[Yy]$ ]] && {
        echo
        rm -fR "$WORKING_DIR"

        kubectl delete deployment.apps/wavefront-proxy service/wavefront-proxy || :

        kubectl delete deployment.apps/kube-state-metrics service/kube-state-metrics -n kube-system || :

        kubectl delete clusterroles.rbac.authorization.k8s.io/kube-state-metrics -n kube-system || :
        kubectl delete clusterrolebindings.rbac.authorization.k8s.io/kube-state-metrics -n kube-system || :
        kubectl delete roles.rbac.authorization.k8s.io/kube-state-metrics-resizer -n kube-system || :
        kubectl delete rolebindings.rbac.authorization.k8s.io/kube-state-metrics -n kube-system || :
        kubectl delete serviceaccounts/kube-state-metrics -n kube-system || :

        kubectl delete deployment.apps/wavefront-collector -n wavefront-collector || :

        kubectl delete namespace/wavefront-collector -n wavefront-collector || :

        kubectl delete clusterroles.rbac.authorization.k8s.io/wavefront-collector -n wavefront-collector || :
        kubectl delete clusterrolebindings.rbac.authorization.k8s.io/wavefront-collector -n wavefront-collector || :
    }
    exit "$EXIT_CODE"
}
trap clean_up EXIT

terminal () {
    [[ "$OSTYPE" =~ darwin* ]] && {
        # shellcheck disable=SC2145
        osascript -e "tell application \"Terminal\" to do script \"$@\""
    }
}

# select a smart cluster and generate kube-config file -----------------------

vke_cluster_auth
echo
NAME=$(kubectl config current-context)
NAME="${NAME/-context/}"

WORKING_DIR="$HOME/tmp/wavefront-$NAME"
mkdir "$WORKING_DIR"
pushd "$WORKING_DIR" > /dev/null || exit 1

# ask for Wavefront URL and Token --------------------------------------------

WAVEFRONT_CONFIG="$HOME/.vke/.wavefront_config"
[[ -d "$(dirname $WAVEFRONT_CONFIG)" ]] || mkdir "$HOME/.vke"
[[ -f "$WAVEFRONT_CONFIG" ]] && {
    WAVEFRONT_HOST_PREFIX="$(grep wavefront_host_prefix $WAVEFRONT_CONFIG | cut -d':' -f2)"
    WAVEFRONT_TOKEN="$(grep wavefront_token $WAVEFRONT_CONFIG | cut -d':' -f2)"
}

read -p "What goes before .wavefront.com as the hostname for your Wavefront URL? [$WAVEFRONT_HOST_PREFIX] " -r
echo
[[ -z $REPLY ]] || WAVEFRONT_HOST_PREFIX="$REPLY"

read -p "What is your Wavefont API Token? [$WAVEFRONT_TOKEN] " -r
echo
[[ -z $REPLY ]] || WAVEFRONT_TOKEN="$REPLY"

echo "wavefront_host_prefix:$WAVEFRONT_HOST_PREFIX" > "$WAVEFRONT_CONFIG"
echo "wavefront_token:$WAVEFRONT_TOKEN" >> "$WAVEFRONT_CONFIG"

echo "Deploying Wavefront proxy and collector on smart cluster $NAME"
echo "Metric data will be pushed to Wavefront server at https://$WAVEFRONT_HOST_PREFIX.wavefront.com/api/"
echo

# deploy wavefront proxy -----------------------------------------------------

heading 'Deploy the Wavefront proxy'

curl -s https://raw.githubusercontent.com/wavefrontHQ/wavefront-kubernetes/master/wavefront-proxy/wavefront.yaml -o wavefront.yaml
sed -i '' "s/value: https:\/\/YOUR_CLUSTER/value: https:\/\/$WAVEFRONT_HOST_PREFIX/" wavefront.yaml
sed -i '' "s/value: YOUR_API_TOKEN/value: $WAVEFRONT_TOKEN/" wavefront.yaml

kubectl create -f wavefront.yaml

# deploy kube-state-metrics service ------------------------------------------

heading 'Deploy the kube-state-metrics service'

curl -s https://raw.githubusercontent.com/wavefrontHQ/wavefront-kubernetes/master/ksm-all-in-one/kube-state.yaml -o kube-state.yaml

kubectl create -f kube-state.yaml

# deploy wavefront collector ------------------------------------------

heading 'Deploy the Wavefont collector'

mkdir wavefront-collector-dir
pushd wavefront-collector-dir > /dev/null || exit 1

curl -s https://raw.githubusercontent.com/wavefrontHQ/wavefront-kubernetes-collector/master/deploy/kubernetes/0-collector-namespace.yaml -o 0-collector-namespace.yaml

curl -s https://raw.githubusercontent.com/wavefrontHQ/wavefront-kubernetes-collector/master/deploy/kubernetes/1-collector-cluster-role.yaml -o 1-collector-cluster-role.yaml

curl -s https://raw.githubusercontent.com/wavefrontHQ/wavefront-kubernetes-collector/master/deploy/kubernetes/2-collector-rbac.yaml -o 2-collector-rbac.yaml

curl -s https://raw.githubusercontent.com/wavefrontHQ/wavefront-kubernetes-collector/master/deploy/kubernetes/3-collector-service-account.yaml -o 3-collector-service-account.yaml

curl -s https://raw.githubusercontent.com/wavefrontHQ/wavefront-kubernetes-collector/master/deploy/kubernetes/4-collector-deployment.yaml -o 4-collector-deployment.yaml
sed -i '' "s/clusterName=k8s-cluster/clusterName=$NAME/" 4-collector-deployment.yaml
#sed -i '' "s/serviceAccountName:/#serviceAccountName:/" 4-collector-deployment.yaml

popd > /dev/null || exit 1

kubectl create -f wavefront-collector-dir

# monitor deployment ---------------------------------------------------------

popd > /dev/null || exit 1

echo -en "\nWaiting for Wavefront Proxy to deploy..."
kubectl wait deployment -l app=wavefront-proxy --for=condition=available > /dev/null
echo "done"
terminal "vke cluster auth setup $NAME && kubectl logs -f $(kubectl -o json get pod -l app=wavefront-proxy | jq -r '.items[].metadata.name')" > /dev/null
echo -en "\nWaiting for Wavefront Collector to deploy..."
kubectl wait deployment -l name=wavefront-collector --for=condition=available -n wavefront-collector > /dev/null
echo "done"
terminal "vke cluster auth setup $NAME && kubectl logs -f $(kubectl -o json get pod -n wavefront-collector | jq -r '.items[].metadata.name') -n wavefront-collector" > /dev/null