#!/usr/bin/env bash
# @file vke_cleanup
# Delete previously created Smart Clusters from a VMware Kubernetes Engine Project.
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

source vke_env.sh

vke_auth

rm -f "${VKE_LOG}"
VKE_CLUSTERS=$(vke -o json cluster list | jq -r '.items[] | .name +":"+ .folderName +":"+ .projectName' | grep "$VKE_CLUSTER_PREFIX")

echo
for cluster in $VKE_CLUSTERS; do
    info=(${cluster//:/ })
    name=${info[0]}
    folder=${info[1]}
    project=${info[2]}
    read -p "Delete $name? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        vke cluster delete "$name" --folder "$folder" --project "$project" 2>&1 >>"${VKE_LOG}" &
    fi
done
