#!/usr/bin/env bash
# @file nimbus_extend_lease.sh
# Extend the lease on a Nimbus testbed
# Generated by nimbus_extend_lease_wrapper.sh
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>
NIMBUS=""
echo "Checking remaining days on the lease of testbed $USER..."
EXP_DATE=
REMAINING=-17648
if [[ "" == '1' ]]; then
    /mts/git/bin/nimbus-ctl --nimbusLocation=sc --lease "7" --testbed extend_lease "$USER"
else
    echo "Still have  days left"
fi
