#!/usr/bin/env bash
# @file show_public_api
# Start swagger ui for data protection show_dp_api
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

[[ -n $DEBUG ]] && set -x
set -eou pipefail

# Need auth to work :(
# OCTL_SWAGGER_URL="https://gitlab.eng.vmware.com/olympus/api/raw/master/public-swagger.yaml"
# OCTL_SWAGGER_FILE="$(basename $OCTL_SWAGGER_URL)"
# curl -OL "$OCTL_SWAGGER_URL" && mv "$OCTL_SWAGGER_FILE" olympus-swagger.yaml

../misc/open_swagger_ui_with ./public-swagger.yaml 8881