#!/usr/bin/env bash
# @file check_name_flag
# Expose --name flag for all commands
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

[[ -n $DEBUG ]] && set -x
set -eou pipefail

fetch_taxo() {
  curl https://raw.githubusercontent.com/ali5ter/cli_taxo/master/exp1/results/tanzu_taxo_with_options.txt -O -s
}

find_wordlist() {
  local extract_word="^.*└──.(.*)"
  local first_level_command="^└──.[^└─]*"
  local command=""
  local new_word=""
  echo "Commands containing --name flag:" > "$REPORT"
  while read -r line; do
    [[ $line =~ $first_level_command ]] && command=''
    [[ $line =~ $extract_word ]] && {
    # [[ "${#BASH_REMATCH[@]}" == 0 ]] || {
      new_word="${BASH_REMATCH[1]}"
      [[ $new_word =~ ^.*--.* ]] || command="$command $new_word"
      [[ $new_word =~ ^.*--name.* ]] && echo "tanzu $command --name" >> "$REPORT"
    }
  done < "$TAXO"
}

cleanup() {
  rm -f "$TAXO"
}

TAXO=./tanzu_taxo_with_options.txt
REPORT=./name_flags.txt

fetch_taxo && find_wordlist && cleanup