#!/usr/bin/env bash
# @file create_cluster_group
# Create a TMC cluster group
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

[[ -n $DEBUG ]] && {
    export PS4='+($(basename ${BASH_SOURCE[0]}):${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -x
}
set -eou pipefail

# shellcheck disable=SC1091
source tanzu_config.sh

# Instructions to understand how the declarative file was created:
# 1. List the available templates
#   tanzu tmc clustergroup template list
# 2. Get the template details
#   tanzu tmc clustergroup template get default
# 3. Create a declarative file using the 'data' section of the template.
#    The rest of the template describes the type of variables used.

CLUSTER_GROUP_YAML=templates/cluster_group.yaml

# START YAML DECLARATION -----------------------------------------------------
cat<<EOF>"$CLUSTER_GROUP_YAML"
type:
  kind: ClusterGroup
  package: vmware.tanzu.manage.v1alpha1.clustergroup
  version: v1alpha1
fullName:
  name: "$TMC_CLUSTER_GROUP"
meta:
  annotations: null
  description: "$TMC_DESCRIPTION"
  labels: "$TMC_LABELS"
EOF
# END YAML DECLARATION -------------------------------------------------------

# Check and create cluster group
if tanzu tmc clustergroup list | grep "$TMC_CLUSTER_GROUP" >/dev/null; then
    echo "Cluster group '$TMC_CLUSTER_GROUP' exists"
else
    tanzu tmc clustergroup create -f "$CLUSTER_GROUP_YAML"
fi