#!/usr/bin/env bash
# @file create_eks_lcm_credential
# Create an eks lcm credential
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

[[ -n $DEBUG ]] && set -x
set -eou pipefail

# shellcheck disable=SC1091
source tanzu_config.sh

EKS_LCM_CREDENTIAL='alb-test-eks-credential'
EKS_LCM_ARN=''
EKS_LCM_CREDENTIAL_INSTRUCTIONS='eks_lcm_setup_instructions.txt'
DATA_VALUES_FILE='eks_lcm_data_values.txt'

# Create an eks lcm credential and save the instructions to a file
tanzu tmc account credential permission-template generate \
    -n "$EKS_LCM_CREDENTIAL" \
    -c MANAGED_K8S_PROVIDER -p AWS_EKS > $EKS_LCM_CREDENTIAL_INSTRUCTIONS

# Parse the AWS CLI commands from the instructions file
AWS_CLI_RUN_STACK=$(cat $EKS_LCM_CREDENTIAL_INSTRUCTIONS | grep "aws cloudformation create-stack" | tr -d '"')
AWS_CLI_GET_ARN_CMD=$(cat $EKS_LCM_CREDENTIAL_INSTRUCTIONS | grep "aws iam get-role" | tr -d '"')

# Run the AWS CLI commands to run the stack and get the ARN
# Note: Need autorization to AWS account before the following commands can be run 
eval "$AWS_CLI_RUN_STACK" && eval "$AWS_CLI_GET_ARN_CMD" > "$EKS_LCM_ARN"

# Create the data values file
echo "Name: $EKS_LCM_CREDENTIAL" >> "$DATA_VALUES_FILE"
echo "Arn: $EKS_LCM_ARN" >> "$DATA_VALUES_FILE"

# Complete the credential creation by providing the ARN
tanzu tmc account credential create --input-template-file lcm-eks --data-values-file "$DATA_VALUES_FILE"