#!/usr/bin/env bash
# @file create_credential_lcm_eks
# Create an eks lcm credential
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

[[ -n $DEBUG ]] && {
    export PS4='+($(basename ${BASH_SOURCE[0]}):${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -x
}
set -eou pipefail

# shellcheck disable=SC1091
source tanzu_config.sh

EKS_LCM_CREDENTIAL='alb-test-eks-credential'
EKS_LCM_ARN=''
EKS_LCM_CREDENTIAL_INSTRUCTIONS='eks_lcm_setup_instructions.txt'
DATA_VALUES_FILE='eks_lcm_data_values.txt'

# Create an eks lcm credential and save the instructions to a file
tanzu tmc account credential permission-template generate \
    -n "$EKS_LCM_CREDENTIAL" \
    -c MANAGED_K8S_PROVIDER -p AWS_EKS > $EKS_LCM_CREDENTIAL_INSTRUCTIONS

# Parse the AWS CLI commands from the instructions file
AWS_CLI_RUN_STACK=$(cat $EKS_LCM_CREDENTIAL_INSTRUCTIONS | \
    grep "aws cloudformation create-stack" | tr -d '"')
# Note: The IAM capability is required to create the IAM role
AWS_CLI_RUN_STACK="$AWS_CLI_RUN_STACK --capabilities CAPABILITY_NAMED_IAM"
# Note: Need lamdas to appear in Oregon region
AWS_CLI_RUN_STACK="$AWS_CLI_RUN_STACK --region us-west-2"
AWS_CLI_GET_ARN_CMD=$(cat $EKS_LCM_CREDENTIAL_INSTRUCTIONS | \
    grep "aws iam get-role" | tr -d '"')
AWS_CF_STACK_NAME=$(cat $EKS_LCM_CREDENTIAL_INSTRUCTIONS | \
    grep "aws cloudformation create-stack" | \
    awk '{print $5}')

# Loop to check state of stack creation
get_stack_status() {
    # shellcheck disable=SC2086
    aws cloudformation list-stacks --region us-west-2 --output json | \
        jq -r --arg STACK $AWS_CF_STACK_NAME 'first(.StackSummaries[] | select(.StackName == $STACK) | .StackStatus)'
}

# Run the AWS CLI commands to run the stack
# Note: Need autorization to AWS account before the following commands can be run 
eval "$AWS_CLI_RUN_STACK"

echo -n 'Waiting for stack to be created...'
while [[ $(get_stack_status) != "CREATE_COMPLETE" ]]; do
    echo -n '.'
    sleep 10
done

# Run the AWS CLI commands get the ARN
# Note: Need autorization to AWS account before the following commands can be run 
EKS_LCM_ARN=$(eval "$AWS_CLI_GET_ARN_CMD")

# Create the data values file
echo "Name: $EKS_LCM_CREDENTIAL" > "$DATA_VALUES_FILE"
echo "Arn: $EKS_LCM_ARN" >> "$DATA_VALUES_FILE"

# Complete the credential creation by providing the ARN
tanzu tmc account credential create \
    --input-template lcm-eks \
    --data-values-file "$DATA_VALUES_FILE"