#!/usr/bin/env bash
# @file current_contexts
# List current contexts
# NOTE: Assumes this is run on macOS with Homebrew installed
# @author Alister Lewis-Bowen <bowena@vmware.com>

[[ -n $DEBUG ]] && set -x
set -eou pipefail

if ! which tanzu &> /dev/null; then
    ./standup_env
fi

# No conveneient way to get current context, so parse the name out of current json
tanzu context list --current -o json | jq -r .[].name

# Display in-line for use in a prompt
# tanzu context list --current -o json | jq -r .[].name | tr '\n' ' '