#!/usr/bin/env bash
# @file tanzufy_cluster
# Install Tanzu Cluster Essentials on a Kind k8s cluster
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>
# @ref https://github.com/vmware-tanzu/tanzu-cli/blob/main/docs/full/context-scoped-plugins.md#when-the-context-is-of-type-kubernetes
# @ref https://docs.vmware.com/en/Cluster-Essentials-for-VMware-Tanzu/1.5/cluster-essentials/deploy.html
# @ref https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/install-online-profile.html

[[ -n $DEBUG ]] && set -x
set -eou pipefail

TANZU_NET_USER="$(cut -d: -f1 "$HOME/.config/tanzu_net_creds")" # change to location of your stored Tanzu Network credentials
TANZU_NET_PASSWORD="$(cut -d: -f2 "$HOME/.config/tanzu_net_creds")" # change to location of your stored Tanzu Network credentials
CLUSTER_NAME="tanzu-cluster"

# shellcheck disable=SC2155
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOWNLOADED_CLUSTER_ESSENTIALS=tanzu-cluster-essentials-darwin-amd64-1.5.1.tgz
CLIPLUGIN_CRD="https://raw.githubusercontent.com/vmware-tanzu/tanzu-cli/v1.0.0/apis/config/crd/bases/cli.tanzu.vmware.com_cliplugins.yaml"
CLIPLUGIN_SUGGESTIONS="$SCRIPT_DIR/cliplugins.yaml"

export INSTALL_REGISTRY_HOSTNAME="registry.tanzu.vmware.com"
export INSTALL_REGISTRY_USERNAME="$TANZU_NET_USER"
export INSTALL_REGISTRY_PASSWORD="$TANZU_NET_PASSWORD"

which brew &> /dev/null || {
  echo "Homebrew not installed"
  exit 1
}
which kubectl &> /dev/null || brew install kubernetes-cli
which kind &> /dev/null || brew install kind
docker stats --no-stream &> /dev/null || open /Applications/Docker.app
 
cleanup() {
  kind delete cluster --name "$CLUSTER_NAME"
  kubectl config get-contexts | grep "kind-$CLUSTER_NAME" &> /dev/null && {
    kubectl config delete-context "kind-$CLUSTER_NAME"
  }
  tanzu context list | grep "$CLUSTER_NAME" &> /dev/null && {
    tanzu context delete "$CLUSTER_NAME" --yes
  } 
  rm -fR tanzu-cluster-essentials
}

create_cluster() {
  kind create cluster --name "$CLUSTER_NAME"
}

install_plugin_suggestions() {
  # Need to install the Tanzu CLIPlugin CRD and provide suggested Tanzu Core
  # CLI plugins to install for a k8s context
  kubectl apply -f "$CLIPLUGIN_CRD"
  kubectl apply -f "$CLIPLUGIN_SUGGESTIONS"
}

install_cluster_essentials() {
  mkdir tanzu-cluster-essentials
  tar -xvf "$DOWNLOADED_CLUSTER_ESSENTIALS" -C tanzu-cluster-essentials
  kubectl config use-context "kind-$CLUSTER_NAME"
  export INSTALL_BUNDLE=registry.tanzu.vmware.com/tanzu-cluster-essentials/cluster-essentials-bundle@sha256:79abddbc3b49b44fc368fede0dab93c266ff7c1fe305e2d555ed52d00361b446
  cd tanzu-cluster-essentials
  ./install.sh --yes
  cd - || exit 1
}

uninstall_cluster_essentials() {
  if [[ ! -d tanzu-cluster-essentials ]]; then
    cd tanzu-cluster-essentials
    ./uninstall.sh --yes
    cd - || exit 1
  fi
}

add_tap_package_repo() {
  export INSTALL_REPO="tanzu-application-platform"
  export TAP_VERSION="1.5.1"
  kubectl create ns tap-install
  tanzu secret registry add tap-registry \
    --server "${INSTALL_REGISTRY_HOSTNAME}" \
    --username "${INSTALL_REGISTRY_USERNAME}" \
    --password "${INSTALL_REGISTRY_PASSWORD}" \
    --namespace tap-install \
    --export-to-all-namespaces \
    --yes 
  tanzu secret registry add registry-credentials \
    --server "${INSTALL_REGISTRY_HOSTNAME}" \
    --username "${INSTALL_REGISTRY_USERNAME}" \
    --password "${INSTALL_REGISTRY_PASSWORD}" \
    --namespace tap-install \
    --export-to-all-namespaces \
    --yes 
  tanzu package repository add tanzu-tap-repository \
    --url ${INSTALL_REGISTRY_HOSTNAME}/${INSTALL_REPO}/tap-packages:$TAP_VERSION \
    --namespace tap-install
}

create_local_cluster_context() {
  tanzu context create --kubeconfig "$HOME/.kube/config" --kubecontext "kind-$CLUSTER_NAME" --name "$CLUSTER_NAME"
  # CLIPlugin resource suggets plugins to install for the kubernetes context
}

cleanup
create_cluster
install_cluster_essentials
install_plugin_suggestions
create_local_cluster_context

kubectl get pods -A

add_tap_package_repo

tanzu package available list -n tap-install