#!/usr/bin/env bash
# @file tanzufy_cluster
# Install Tanzu Cluster Essentials on a Kind k8s cluster
# @author Alister Lewis-Bowen <bowena@vmware.com>
# @ref https://docs.vmware.com/en/Cluster-Essentials-for-VMware-Tanzu/1.5/cluster-essentials/deploy.html

[[ -n $DEBUG ]] && set -x
set -eou pipefail

DOWNLOADED_CLUSTER_ESSENTIALS=tanzu-cluster-essentials-darwin-amd64-1.5.0.tgz
TANZU_NET_USER="$(cut -d: -f1 "$HOME/.config/tanzu_net_creds")" # change to location of your stored Tanzu Network credentials
TANZU_NET_PASSWORD="$(cut -d: -f2 "$HOME/.config/tanzu_net_creds")" # change to location of your stored Tanzu Network credentials
CLUSTER_NAME="tanzu-cluster"

which brew &> /dev/null || {
  echo "Homebrew not installed"
  exit 1
}
which kubectl &> /dev/null || brew install kubernetes-cli
which kind &> /dev/null || brew install kind
docker stats --no-stream &> /dev/null || open /Applications/Docker.app

cleanup() {
  kind delete cluster --name "$CLUSTER_NAME"
  rm -fR tanzu-cluster-essentials  
}

create_cluster() {
  kind create cluster --name "$CLUSTER_NAME"
}

install_cluster_essentials() {
  mkdir tanzu-cluster-essentials
  tar -xvf "$DOWNLOADED_CLUSTER_ESSENTIALS" -C tanzu-cluster-essentials
  kubectl config use-context "kind-$CLUSTER_NAME"
  export INSTALL_BUNDLE=registry.tanzu.vmware.com/tanzu-cluster-essentials/cluster-essentials-bundle@sha256:79abddbc3b49b44fc368fede0dab93c266ff7c1fe305e2d555ed52d00361b446
  export INSTALL_REGISTRY_HOSTNAME=registry.tanzu.vmware.com
  export INSTALL_REGISTRY_USERNAME="$TANZU_NET_USER"
  export INSTALL_REGISTRY_PASSWORD="$TANZU_NET_PASSWORD"
  cd tanzu-cluster-essentials
  ./install.sh --yes
}

create_local_cluster_context() {
  tanzu context create --kubeconfig "$HOME/.kube/*" --kubecontext "kind-$CLUSTER_NAME" --name local-kind-cluster
}

cleanup && create_cluster && install_cluster_essentials && create_local_cluster_context