#!/usr/bin/env bash
# @file generate_word_string
# Word string generator using system dictionary
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

## Convenience aliases
alias wstring='generate_word_string'

generate_word_string() {
    local wordFiles="/usr/share/dict/words"
    # shellcheck disable=SC2155
    local totalWords=$(awk 'NF!=0 {++c} END {print c}' $wordFiles)
    local numWords=${1:-3}
    local delim=${2:--}

    local string=''
    # shellcheck disable=SC2034
    # shellcheck disable=SC2086
    for i in $(seq $numWords); do
        rnum=$(perl -e 'print int rand $ARGV[0], "\n"; ' -- "$totalWords")
        word=$(sed -n "$rnum p" $wordFiles)
        if [ "$string" == "" ]; then string="$word"
        else string="${string}${delim}$word"
        fi
    done
    echo "$string" | sed s/\'//g | tr '[:upper:]' '[:lower:]'
}

[ "${BASH_SOURCE[0]}" -ef "$0" ] && generate_word_string "$@"