#!/usr/bin/env bash
# Bash completion for cascade CLI command
# Generated by cli_taxo

_cascade_complete () {

    local cur="${COMP_WORDS[COMP_CWORD]}"
    local prev="${COMP_WORDS[COMP_CWORD-1]}"

    echo "${COMP_WORDS[@]}" | grep -q '-' && {
        i=0
        until echo "${COMP_WORDS[i]}" | grep -q '-' ; do ((i++)); done
        prev="${COMP_WORDS[i-1]}"
    }
    
    case "$prev" in
                rename)    cmds="--folder --project";;
        set)    cmds="--folder";;
        show)    cmds="--folder --folder --perf --folder --project --folder --project --folder --project --folder --project";;
        cluster)    cmds="create show list resize rename delete upgrade get-kubectl-auth merge-kubectl-auth iam --help";;
        export)    cmds="--output --output --output --folder --output --folder --project --output --folder --project";;
        merge-kubectl-auth)    cmds="--folder --project";;
        iam)    cmds="show export import add remove --help role --help show export import add remove --help show export import add remove --help show export import add remove --help show export import add remove --help";;
        upgrade)    cmds="--version --folder --project";;
        group)    cmds="create delete show list user --help";;
        create)    cmds="--description --display-name --display-name --folder --name --service-level --display-name --size --container-network --region --version --template --folder --project --folder --project";;
        namespace)    cmds="create delete show list iam --help";;
        add)    cmds="--subject --role --user-name --subject --role --subject --role --folder --subject --role --folder --project --subject --role --folder --project";;
        version)    cmds="list --help";;
        role)    cmds="list --help";;
        resize)    cmds="--folder --project";;
        template)    cmds="list --help";;
        import)    cmds="--input --input --input --folder --input --folder --project --input --folder --project";;
        folder)    cmds="create delete show get set list iam --help";;
        get)    cmds="--folder";;
        user)    cmds="show list --help add remove list --help";;
        tenant)    cmds="show iam --help";;
        get-kubectl-auth)    cmds="--configfile --folder --project";;
        target)    cmds="login --help";;
        region)    cmds="list --help";;
        list)    cmds="--folder --folder --project --folder --project --region";;
        remove)    cmds="--subject --role --user-name --subject --role --subject --role --folder --subject --role --folder --project --subject --role --folder --project";;
        project)    cmds="create delete show get set list iam --help";;
        cascade)    cmds="region target tenant user group iam folder project cluster namespace version template help --non-interactive --log-file --output --detail --help --version";;
        login)    cmds="--tenant --refresh-token";;
        delete)    cmds="--folder --folder --project --folder --project";;
        *)    cmds="rename set show cluster export merge-kubectl-auth iam upgrade group create namespace add version role resize template import folder get user tenant get-kubectl-auth target region list remove project cascade login delete";;
    esac

    COMPREPLY=( $(compgen -W "$cmds" -- "$cur") )

    return 0
}

complete -F _cascade_complete cascade

