#!/usr/bin/env bash
# @file cluster_secret
# Example of how to run an inspection on a TMC managed k8s cluster
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

# shellcheck disable=SC1091
source tmc_env.sh

# functions ------------------------------------------------------------------


# Check what cluster to play with --------------------------------------------

set_up

set_cluster

# run a conformance inspection scan if non are running -----------------------

heading "foo"

