#!/usr/bin/env bash
# @file playground
# Scratchpad of tmc commands while testing
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

# shellcheck disable=SC1091
source tmc_env.sh

# stand up env ---------------------------------------------------------------

set_up

context_detail

start_local_cluster

attach_local_cluster

# play with policies ---------------------------------------------------------

heading "Add some policies to the cluster"

# Add access policy
# !! Inconsistent use of positional arg for cluster name
# !! Be nice if there was a role binding name
echo "Add an access policy role binding to allow a user to edit this cluster"
erun tmc cluster iam add-binding "$TMC_CLUSTER_NAME" \
    -m attached -p attached \
    -r cluster.edit -u bowena@vmware.com

# List access policies
# !! No list command
# tmc cluster iam list \
#     --clust
# kubectl get rolebindings,clusterrolebinding \
#     --all-namespaces | grep cluster.edit

# Add security policy
# !! No autocomplete for security-policy subcommand
# !! Help doesn't talk about cluster name flag
# !! No name parameter
echo "Add a security policy for baseline lockdown of the cluster"
erun tmc cluster security-policy create \
    --cluster-name "$TMC_CLUSTER_NAME" -m attached -p attached \
    -r baseline

# List security policies
# !! No autocomplete for security-policy subcommand
erun tmc cluster security-policy list \
    --cluster-name "$TMC_CLUSTER_NAME" -m attached -p attached
    
# run a default (lite) inpection scan ----------------------------------------

heading "Run a minimal inspection scan on the cluster"

read -p "${TMC_BOLD}✋ A scan can take a while to run. Do you want to run one now? [y/N] ${TMC_RESET}" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    # Run a lite inspection scan
    # !! Have to parse out the scan name
    scanName="$(tmc cluster inspection scan create \
        -c "$TMC_CLUSTER_NAME" -m attached -p attached \
        | tail -n 1 | cut -d'"' -f2)"
    echo "Lite inspection scan, $scanName, started"
    echo

    # !! List command doesn't include -c option

    echo -n "Monitoring the inspection scan"
    # !! Why does cluster need to be defined?
    # shellcheck disable=SC2086 
    while [ "$(tmc cluster inspection scan get $scanName \
        --cluster-name $TMC_CLUSTER_NAME -m attached -p attached \
        -o json | jq -r .status.phase)" != "COMPLETE" ]; do
        echo -n '.'
        sleep 10
    done
    echo ' ✅'
    echo

    erun tmc cluster inspection scan get "$scanName" \
        --cluster-name "$TMC_CLUSTER_NAME" -m attached -p attached \
        -o json | jq -r .status.conditions.READY.message
fi

# deploy an application and bring its namespace under TMC management

"${TMC_SCRIPT_DIR}/manage_namespace"

# TODO: Enable TO or TSM integration on this cluster

clean_up