#!/usr/bin/env bash
# @file playground
# Scratchpad of tmc commands while testing
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

# shellcheck disable=SC1091
source tmc_env.sh

# stand up env ---------------------------------------------------------------

set_up

context_detail

start_local_cluster

heading "Create cluster group $TMC_CLUSTER_GROUP unless it exists"

# Create cluster group to manage policy on this cluster
if tmc clustergroup list --all | grep "$TMC_CLUSTER_GROUP" >/dev/null; then
    echo "Cluster group $TMC_CLUSTER_GROUP exists"
else
    # !! name is not positional parameter
    # !! what does 'stringToString' mean in the help?
    erun tmc clustergroup create \
        -n "$TMC_CLUSTER_GROUP" -d "$TMC_DESCRIPTION" -l "$TMC_LABELS"
fi

# attach local cluster -------------------------------------------------------

heading "Attach local k8s cluster it isn't already"

# Bring local cluster under TMC management
if ! tmc cluster list --all | grep "$TMC_CLUSTER_NAME" >/dev/null; then
    # !! name is not positional parameter
    # !! no description option
    # !! can't get label option to work
    # !! what does 'stringToString' mean in the help?
    erun tmc cluster attach -n "$TMC_CLUSTER_NAME" -g "$TMC_CLUSTER_GROUP"
    #    -d "$TMC_DESCRIPTION" -l "$TMC_LABELS"
    sleep 5
    erun kubectl apply -f k8s-attach-manifest.yaml
    rm k8s-attach-manifest.yaml

    # List tmc pods and services before connection to TMC
    erun kubectl get pods,svc -n vmware-system-tmc

    # Check if TMC can see this cluster
    # !! output flag not documented
    echo -n "Checking TMC thinks $TMC_CLUSTER_NAME is ready"
    # shellcheck disable=SC2086
    while [ "$(tmc cluster get $TMC_CLUSTER_NAME \
            -m attached -p attached \
            -o json | jq -r .status.phase)" != 'READY' ]; do
        echo -n '.'
        sleep 10
    done
    echo ' ✅'
    echo

    # List tmc pods and services after connection to TMC
    erun kubectl get pods,svc -n vmware-system-tmc

    # Check if TMC can see this cluster
    # !! output flag not documented
    echo -n "Checking TMC thinks $TMC_CLUSTER_NAME is healthy"
    # shellcheck disable=SC2086
    while [ "$(tmc cluster get $TMC_CLUSTER_NAME \
            -m attached -p attached \
            -o json | jq -r .status.health)" != 'HEALTHY' ]; do
        echo -n '.'
        sleep 10
    done
    echo ' ✅'
    echo
fi

# Inspect cluster
erun tmc cluster get "$TMC_CLUSTER_NAME" -m attached -p attached

# play with policies ---------------------------------------------------------

heading "Add some policies to the cluster"

# Add access policy
# !! Inconsistent use of positional arg for cluster name
# !! Be nice if there was a role binding name
echo "Add an access policy role binding to allow a user to edit this cluster"
erun tmc cluster iam add-binding "$TMC_CLUSTER_NAME" \
    -m attached -p attached \
    -r cluster.edit -u bowena@vmware.com

# List access policies
# !! No list command
# tmc cluster iam list \
#     --clust
# kubectl get rolebindings,clusterrolebinding \
#     --all-namespaces | grep cluster.edit

# Add security policy
# !! No autocomplete for security-policy subcommand
# !! Help doesn't talk about cluster name flag
# !! No name parameter
echo "Add a security policy for baseline lockdown of the cluster"
erun tmc cluster security-policy create \
    --cluster-name "$TMC_CLUSTER_NAME" -m attached -p attached \
    -r baseline

# List security policies
# !! No autocomplete for security-policy subcommand
erun tmc cluster security-policy list \
    --cluster-name "$TMC_CLUSTER_NAME" -m attached -p attached
    
# run a default (lite) inpection scan ----------------------------------------

heading "Run a minimal inspection scan on the cluster"

read -p "✋ A scan can take a while to run. Do you want to run one now? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    # Run a lite inspection scan
    # !! Have to parse out the scan name
    scanName="$(tmc cluster inspection scan create \
        -c "$TMC_CLUSTER_NAME" -m attached -p attached \
        | tail -n 1 | cut -d'"' -f2)"
    echo "Lite inspection scan, $scanName, started"
    echo

    # !! List command doesn't include -c option

    echo -n "Monitoring the inspection scan"
    # !! Why does cluster need to be defined?
    # shellcheck disable=SC2086 
    while [ "$(tmc cluster inspection scan get $scanName \
        --cluster-name $TMC_CLUSTER_NAME -m attached -p attached \
        -o json | jq -r .status.phase)" != "COMPLETE" ]; do
        echo -n '.'
        sleep 10
    done
    echo ' ✅'
    echo

    erun tmc cluster inspection scan get "$scanName" \
        --cluster-name "$TMC_CLUSTER_NAME" -m attached -p attached \
        -o json | jq -r .status.conditions.READY.message
fi

# Bring application namespace under management -------------------------------

deploy_application
namespace='nb'

heading "Bring app namespace under management"

# Create a workspace where we can manage namespaces
# !! --all flag doesn't seem to make any difference
if tmc workspace list --all | grep "$TMC_WORKSPACE" >/dev/null; then
    echo "Workspace $TMC_WORKSPACE exists"
else
    # !! Shouldn't name be a positional parameter?
    # !! what does 'stringToString' mean in the help?
    erun tmc workspace create -n "$TMC_WORKSPACE" \
        -d "$TMC_DESCRIPTION" -l "$TMC_LABELS"
    erun workspace get "$TMC_WORKSPACE"
fi

# !! TMC list command doesn't appear to list any namespaces
tmc cluster namespace get "$namespace" \
    --cluster-name "$TMC_CLUSTER_NAME" -m attached -p attached \
    1>/dev/null 2>/dev/null || {
    # Bring new namespace under TMC management
    # !! Shouldn't name be a positional parameter?
    # !! Why is 'k' used as option for workspace name?
    erun tmc cluster namespace attach -n "$namespace" -k "$TMC_WORKSPACE" \
        -c "$TMC_CLUSTER_NAME" -m attached -p attached \
        -d "$TMC_DESCRIPTION" -l "$TMC_LABELS"
    # !! List command does not list any namespaces!
    # !! No -c option
    erun tmc cluster namespace list \
        --cluster-name "$TMC_CLUSTER_NAME" -m attached -p attached

    # Check if TMC has atached this namespace
    echo -n "Checking TMC thinks $namespace is attached"
    # shellcheck disable=SC2086
    while [ "$(tmc cluster namespace get "$namespace" \
            --cluster-name "$TMC_CLUSTER_NAME" -m attached -p attached \
            -o json | jq -r .status.phase)" == 'ATTACHING' ]; do
        echo -n '.'
        sleep 10
    done
    echo ' ✅'
    echo
}

erun tmc workspace get "$TMC_WORKSPACE"

# !! No -c option
# !! Can not get namespaces which are unmanaged, only those that are managed
erun tmc cluster namespace get "$namespace" \
    --cluster-name "$TMC_CLUSTER_NAME" -m attached -p attached

# TODO: Enable TO or TSM integration on this cluster

clean_up