#!/usr/bin/env bash
# @file playground
# Stand up a TMC managed k8s cluster and auth with TMC API
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

# shellcheck disable=SC1091
source tmc_env.sh

export CLUSTER_TYPES='Local
AWS-EC2'
export CLUSTER_TYPE=''
export CREDENTIAL=''

# functions ------------------------------------------------------------------

get_provisioner() {
    tmc managementcluster provisioner list \
        --management-cluster-name "$TMC_MNGMT_CLUSTER" \
        | fzf --height=40% --layout=reverse --info=inline --border
}

# shellcheck disable=SC2120
get_host_aws_credential() {
    local provisioner="${1:-$TMC_PROVISIONER}"
    # !! Thought there might be a way to list accounts credentials under
    #    tmc managementcluster
    tmc account management-cluster provisioner credential list \
        --management-cluster-name "$TMC_MNGMT_CLUSTER" \
        --provisioner-name "$provisioner" -o json \
        | jq -r .credentials[].fullName.name \
        | fzf --height=40% --layout=reverse --info=inline --border
}

set_up

heading "Context detail"
context_detail

# Deploy a k8s cluster that is managed by TMC --------------------------------

heading "Deploy k8s cluster you want TMC to manage"

echo "${TMC_BOLD}✋ Select the type of k8s cluster you want TMC to manage"
CLUSTER_TYPE=$(echo "$CLUSTER_TYPES" | fzf --height=40% --layout=reverse --info=inline --border)
echo "'$CLUSTER_TYPE' selected"
echo

case "$CLUSTER_TYPE" in
    Local)
        start_local_cluster
        attach_local_cluster
        ;;
    AWS-EC2)
        # Adjust the cluster name to indicate the provider
        set_provider_to aws
        # Adjust for the TMC AWS-Hosted management cluster name
        # !! Guess this is just something you gatta know
        export TMC_MNGMT_CLUSTER='aws-hosted'

        if tmc cluster list --all | grep "$TMC_MNGMT_CLUSTER" | grep -q "$TMC_CLUSTER_NAME"; then
            echo "✅ Cluster $TMC_CLUSTER_NAME exists"
        else
            # Assumes the provisioner is already created (via the UI)
            # !! When creating a provisioner using
            #    tmc account management-cluster provisioner credential create
            #    the default template asks for ARN and other input that I don't understand
            # !! Does anyone know what a provisioner does in this context?
            echo "${TMC_BOLD}✋ Please select a suitable provisioner for LCM on EC2 ${TMC_RESET}"
            # shellcheck disable=SC2155
            export TMC_PROVISIONER=$(get_provisioner | xargs)
            echo "'$TMC_PROVISIONER' selected"
            echo

            echo "${TMC_BOLD}✋ Please select a suitable account credential for LCM on EC2 ${TMC_RESET}"
            # shellcheck disable=SC2119
            CREDENTIAL=$(get_host_aws_credential)
            echo "'$CREDENTIAL' selected"
            echo

            # Found out that the 'default' template creates the TMC AWS-Hosted k8s cluster using
            #   tmc cluster template list
            # then
            #   tmc cluster template get default
            # to see what the template was looking for.
            # You can also run the cluster create in interactive mode to prompt you for input using
            #   tmc cluster create --template default --interactive
            # !! You still have to know what all the inputs are, so here you'd need to know all
            #    the details from your AWS account (which is automatically fetched in the UI)
            erun tmc cluster create -t default --name "$TMC_CLUSTER_NAME" \
                --management-cluster-name "$TMC_MNGMT_CLUSTER" \
                --provisioner-name "$TMC_PROVISIONER" \
                --cluster-group "$TMC_CLUSTER_GROUP" \
                --description "$TMC_DESCRIPTION" \
                --labels "$TMC_LABELS" \
                --account-name "$CREDENTIAL" \
                --ssh-key-name "$AWS_SSH_KEY" \
                --region "$AWS_REGION" \
                --availability-zone "$AWS_AZ" \
                --version "$AWS_K8S_VERSION"

            # Check if TMC can see this cluster
            # !! output flag not documented
            echo -n "Checking TMC thinks $TMC_CLUSTER_NAME is ready"
            # shellcheck disable=SC2086
            while [ "$(tmc cluster get $TMC_CLUSTER_NAME \
                    -m "$TMC_MNGMT_CLUSTER" -p "$TMC_PROVISIONER" \
                    -o json | jq -r .status.phase)" != 'READY' ]; do
                echo -n '.'
                sleep 10
            done
            echo ' ✅'
            echo

            # Check if TMC installed agents provide healthy status
            # !! output flag not documented
            echo -n "Checking TMC thinks $TMC_CLUSTER_NAME is healthy"
            # shellcheck disable=SC2086
            while [ "$(tmc cluster get $TMC_CLUSTER_NAME \
                    -m "$TMC_MNGMT_CLUSTER" -p "$TMC_PROVISIONER" \
                    -o json | jq -r .status.health)" != 'HEALTHY' ]; do
                echo -n '.'
                sleep 10
            done
            echo ' ✅'
            echo
        fi
        ;;
    *)
        echo "😱 Unable to support type '$CLUSTER_TYPE'. Sorry."
        exit 1
        ;;
esac