#!/usr/bin/env bash
# @file tear_down
# Detach/delete TMC managed k8s clusters and remove local k8s cluster
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

# shellcheck disable=SC1091
source tmc_env.sh

# Check what cluster to play with --------------------------------------------

check_stack

# Clear up all the stuffs ----------------------------------------------------

clean_up